import type { RuleManifest } from "@/types/harness-manifest";

export const LOCAL_RULES: RuleManifest[] = [
  {
    id: "rule-require-acceptance-criteria",
    name: "require-acceptance-criteria",
    description: "Every task must have at least one acceptance criterion before a run can start.",
    scope: "task",
    status: "active",
    enforcement: "hard",
    condition_summary: "task.acceptance_criteria is non-empty",
    violation_message: "Cannot start run: task has no acceptance criteria.",
  },
  {
    id: "rule-founder-review-required",
    name: "founder-review-required",
    description: "Artifacts touching security or architecture domains require explicit founder review.",
    scope: "project",
    status: "active",
    enforcement: "hard",
    condition_summary: "artifact.domain in [security, architecture] → approval.state = approved",
    violation_message: "Founder review required for security/architecture artifacts.",
  },
  {
    id: "rule-security-check-before-deploy",
    name: "security-check-before-deploy",
    description: "Deployment cannot proceed unless the latest security check suite has passed.",
    scope: "project",
    status: "active",
    enforcement: "hard",
    condition_summary: "check_suite.status = passed AND check_suite.provider = security",
    violation_message: "Deployment blocked: security check suite not passed.",
  },
  {
    id: "rule-no-self-modification",
    name: "no-self-modification",
    description: "No agent may modify its own prompt, skills, or guidance without founder approval.",
    scope: "system",
    status: "active",
    enforcement: "hard",
    condition_summary: "mutation.target = agent_self → requires founder approval",
    violation_message: "Self-modification blocked: founder approval required.",
  },
  {
    id: "rule-max-retry-budget",
    name: "max-retry-budget",
    description: "A single task run may not exceed 3 automatic retries before escalation.",
    scope: "task",
    status: "active",
    enforcement: "soft",
    condition_summary: "run.retry_count <= 3",
    violation_message: "Retry budget exceeded — escalate to founder.",
  },
];
