import type { HookManifest } from "@/types/harness-manifest";

export const LOCAL_HOOKS: HookManifest[] = [
  {
    id: "hook-verify-before-release",
    name: "verify-before-release",
    description: "Run verification rail checks before any artifact is marked as release-ready.",
    trigger: "before_release",
    scope: "project",
    status: "active",
    action_summary: "Execute verification rail; block release if any check fails.",
    requires_founder_approval: false,
  },
  {
    id: "hook-escalate-on-risk",
    name: "escalate-on-risk",
    description: "Automatically surface high-risk signals to the founder inbox when detected.",
    trigger: "on_risk_detected",
    scope: "project",
    status: "active",
    action_summary: "Create founder notification with risk context and recommended action.",
    requires_founder_approval: false,
  },
  {
    id: "hook-snapshot-context-on-run-start",
    name: "snapshot-context-on-run-start",
    description: "Capture a context snapshot when a new run begins for reproducibility.",
    trigger: "on_run_start",
    scope: "task",
    status: "active",
    action_summary: "Assemble and store a context pack tied to the run.",
    requires_founder_approval: false,
  },
  {
    id: "hook-notify-on-stalled-run",
    name: "notify-on-stalled-run",
    description: "Alert when a run exceeds its expected duration without progress.",
    trigger: "on_run_stalled",
    scope: "system",
    status: "active",
    action_summary: "Flag run as stalled; add to diagnostics dashboard.",
    requires_founder_approval: false,
  },
  {
    id: "hook-guidance-check-on-task-assign",
    name: "guidance-check-on-task-assign",
    description: "Verify that the assigned agent has an active guidance pack before task execution.",
    trigger: "on_task_assign",
    scope: "task",
    status: "draft",
    action_summary: "Warn if agent lacks active guidance; suggest calibration.",
    requires_founder_approval: true,
  },
];
