import type { CommandManifest } from "@/types/harness-manifest";

export const LOCAL_COMMANDS: CommandManifest[] = [
  {
    id: "cmd-force-review",
    name: "force-review",
    description: "Manually trigger a founder review on any artifact or task output.",
    scope: "project",
    status: "active",
    invoked_by: "founder",
    effect_summary: "Creates a pending approval record and notifies the review queue.",
    requires_confirmation: false,
  },
  {
    id: "cmd-escalate-risk",
    name: "escalate-risk",
    description: "Flag a task or run as high-risk, surfacing it in the founder inbox.",
    scope: "task",
    status: "active",
    invoked_by: "agent",
    effect_summary: "Sets risk_flag on the entity and creates a founder notification.",
    requires_confirmation: true,
  },
  {
    id: "cmd-freeze-deployment",
    name: "freeze-deployment",
    description: "Halt all pending deployments for a project until founder lifts the freeze.",
    scope: "project",
    status: "active",
    invoked_by: "founder",
    effect_summary: "Sets project deploy_freeze flag; blocks deployment transitions.",
    requires_confirmation: true,
  },
  {
    id: "cmd-request-context-pack",
    name: "request-context-pack",
    description: "Ask the system to assemble a fresh context pack for a given task.",
    scope: "task",
    status: "active",
    invoked_by: "agent",
    effect_summary: "Triggers context pack assembly from current project state.",
    requires_confirmation: false,
  },
  {
    id: "cmd-publish-guidance",
    name: "publish-guidance",
    description: "Promote a draft guidance pack to active status for a project or employee.",
    scope: "project",
    status: "draft",
    invoked_by: "founder",
    effect_summary: "Marks guidance pack as canonical; agents will reference it.",
    requires_confirmation: true,
  },
];
